services:
  db:
    image: postgres:14.3
    container_name: teslodb
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: MyPassword
      POSTGRES_DB: teslo-shop
      POSTGRES_USER: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: